import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/shared/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-zinc-950 text-zinc-100 overflow-x-hidden">
        <div
          className="fixed -top-40 -left-40 w-125 h-125
    bg-blue-500/30 rounded-full blur-[120px] pointer-events-none z-0"
        />

        <div
          className="fixed -bottom-40 -right-40 w-125 h-125
    bg-indigo-500/30 rounded-full blur-[120px] pointer-events-none z-0"
        />

        <div className="relative z-10">
          <Nav />
          <main className="pt-20">{children}</main>
        </div>
      </body>
    </html>
  );
}
